### ISSUE TITLE
コマンド及びコメント入力欄が太くなってしまうバグ

### ISSUE THREAD

**Issue by kiritannplum** [inonote/nico-rekari-comment-panel-userscript#4]
タイトルの通りですが、コマンド及びコメント入力欄が太くなってしまいます。
調べたところ、画像の要素に元はない
padding: 8px;
が入っていることが原因のように思えます。

![image](https://github.com/inonote/nico-rekari-comment-panel-userscript/assets/52336390/fd1eb569-72cf-44a6-9ea5-7de9f99a859b)

**Comment by inonote** [comment]
ありがとうございます。修正しました。 698645bb55ad978128b8fd2b361f939e1f757bdb 
どうやらクライアントのアップデートでもともと指定されていたpaddingの値に変更があったようで、この影響によりこの問題が発生していました。
